# The only point of copying this rust block is to enable gpt
[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
shebangs = ["rust-script", "cargo"]
auto-format = true
comment-tokens = ["//", "///", "//!"]
block-comment-tokens = [
  { start = "/*", end = "*/" },
  { start = "/**", end = "*/" },
  { start = "/*!", end = "*/" },
]
language-servers = [ "rust-analyzer", "gpt" ] # gpt is the only change
indent = { tab-width = 4, unit = "    " }
persistent-diagnostic-sources = ["rustc", "clippy"]

[language-server.rust-analyzer.config]
check.command = "clippy"

# Enable LSP for zelix log files, which have file names like
# zelix.log.YYYY-MM-DD
[[language]]
name = "log"
scope = "source.log"
file-types = ["log", { glob = "zelix.log.*" } ]

