# The only point of copying this rust block is to enable gpt
[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
shebangs = ["rust-script", "cargo"]
auto-format = true
comment-tokens = ["//", "///", "//!"]
block-comment-tokens = [
  { start = "/*", end = "*/" },
  { start = "/**", end = "*/" },
  { start = "/*!", end = "*/" },
]
language-servers = ["rust-analyzer", "gpt"] # gpt is the only change
indent = { tab-width = 4, unit = "    " }
persistent-diagnostic-sources = ["rustc", "clippy"]

[language-server.rust-analyzer.config]
check.command = "clippy"

# Enable LSP for zelix log files, which have file names like
# zelix.log.YYYY-MM-DD
[[language]]
name = "log"
scope = "source.log"
file-types = ["log", { glob = "zelix.log.*" }]

[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = [
  "md",
  "markdown",
  "mkd",
  "mdwn",
  "mdown",
  "markdn",
  "mdtxt",
  "mdtext",
  "workbook",
  { glob = "PULLREQ_EDITMSG" },
]
roots = [".marksman.toml"]
language-servers = ["markdown-oxide", "ltex-ls", "gpt"]
indent = { tab-width = 2, unit = "  " }
block-comment-tokens = { start = "<!--", end = "-->" }
formatter = { command = 'prettier', args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "never",
] }
auto-format = true
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true

[language-server.ltex-ls.config.ltex.dictionary]
"en-US" = [
  "Alacritty",
  "difftastic",
  "Difftastic",
  "Zelix",
  "Zellij",
  "Broot",
  "subcommand",
  "subcommands",
  "Subcommands",
  "Neovim",
]
