# The Zellij session for your project. Rename this for your own projects.
session = "zelix"

# Configuration of the open subcommand
[open]

# Open in the current terminal
# terminal = [] 

# New window with alacritty
# terminal = ["alacritty", "--command"]

# New window with kitty
# terminal = [ "kitty" ]

# New window with foot. Very fast and low-memory. But no colored undercurls, 
# so it's bad for LSP diagnostics.
# terminal = [ "foot", "--" ]

# New window with foot, in client-server mode
# terminal = [ "footclient", "--" ]

# New window with wezterm. Extremely feature-rich terminal, but for unknown
# reason `wezterm start -- zellij ...` doesn't work for me. So the setting
# below fails
# terminal = [ "wezterm", "start", "--" ]
